spring:
  application:
    name: Payment Microservices
  datasource:
    url: jdbc:postgresql://localhost:5433/main_database?createDatabaseIfNotExist=true
    username: postgres
    password: root
  jpa:
    show-sql: true